use axum::http::StatusCode;
use axum::response::Json;
use axum::response::{IntoResponse, Response};
use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorOutput {
    pub error: String,
}

#[derive(Error, Debug)]
pub enum AppError {
    #[error("email already exists: {0}")]
    EmailAlreadyExists(String),

    #[error("sql error: {0}")]
    SqlxError(#[from] sqlx::Error),

    #[error("password hash error: {0}")]
    PasswordHashError(#[from] argon2::password_hash::Error),

    #[error("jwt error: {0}")]
    JwtError(#[from] jwt_simple::Error),

    #[error("http header parse error: {0}")]
    HttpHeaderError(#[from] axum::http::header::InvalidHeaderValue),
}

// AppError represents all errors your application can produce, including:
// Programmer-created errors: EmailAlreadyExists(String) — you explicitly define this
// System component errors: SqlxError, JwtError, PasswordHashError, etc. — caught from external libraries via #[from]

// ErrorOutput is just the serialization wrapper for sending error messages to HTTP clients.

// Both programmer-created (EmailAlreadyExists) and system errors (SqlxError) become AppError variants. Then ErrorOutput standardizes them all for HTTP responses.

impl ErrorOutput {
    pub fn new(error: impl Into<String>) -> Self {
        Self {
            error: error.into(),
        }
    }
}

// IntoResponse converts it
impl IntoResponse for AppError {
    fn into_response(self) -> Response<axum::body::Body> {
        let status = match &self {
            Self::SqlxError(_) => StatusCode::INTERNAL_SERVER_ERROR,
            Self::PasswordHashError(_) => StatusCode::UNPROCESSABLE_ENTITY,
            Self::JwtError(_) => StatusCode::FORBIDDEN,
            Self::HttpHeaderError(_) => StatusCode::UNPROCESSABLE_ENTITY,
            Self::EmailAlreadyExists(_) => StatusCode::CONFLICT,
        };

        // All AppErrors → single ErrorOutput format
        (status, Json(ErrorOutput::new(self.to_string()))).into_response()
    }
}

// Display for AppError is automatically generated by the thiserror crate based on the #[error(...)] annotations. So when you call .to_string() on an AppError, it formats the error message according to those annotations, including any data from the enum variants.

// Concrete Example
// When you have:
// #[derive(Error, Debug)]
// pub enum AppError {
//     #[error("email already exists: {0}")]
//     EmailAlreadyExists(String),

//     #[error("jwt error: {0}")]
//     JwtError(#[from] jwt_simple::Error),
// }
// The thiserror crate automatically generates a Display impl:
// // Generated by thiserror
// impl Display for AppError {
//     fn fmt(&self, f: &mut Formatter) -> fmt::Result {
//         match self {
//             AppError::EmailAlreadyExists(email) => {
//                 write!(f, "email already exists: {}", email)
//             }
//             AppError::JwtError(err) => {
//                 write!(f, "jwt error: {}", err)
//             }
//         }
//     }
// }
// Then when you call .to_string():
// impl ToString for T where T: Display {
//     fn to_string(&self) -> String {
//         Display::fmt(self, &mut String::new()).to_string()
//     }
// }
// It uses the generated Display impl to convert the enum variant + data into a formatted string.

// Example Output
// let err = AppError::EmailAlreadyExists("tchen@acme.org".to_string());
// println!("{}", err.to_string());
// // Output: "email already exists: tchen@acme.org"

// let err2 = AppError::JwtError(some_jwt_error);
// println!("{}", err2.to_string());
// // Output: "jwt error: token expired"

// In Your Code
// impl IntoResponse for AppError {
//     fn into_response(self) -> Response {
//         let status = match &self { ... };
//         // self.to_string() extracts the formatted error message
//         (status, Json(ErrorOutput::new(self.to_string()))).into_response()
//     }
// }

// So when you return Err(AppError::EmailAlreadyExists("test@example.com".to_string())), it becomes:
// {
//   "error": "email already exists: test@example.com"
// }

// TL;DR: thiserror macro generates a Display impl from your #[error(...)] annotations, so .to_string() just formats the enum variant and its data into the message you specified.

// Json(ErrorOutput::new(self.to_string())) vs Json(self.to_string())

// # Difference: `ErrorOutput` vs Direct String

// You're right to question it. Let me show the difference:

// ## Current Code
// ```rust
// Json(ErrorOutput::new(self.to_string()))
// ```

// **Response:**
// ```json
// {
//   "error": "email already exists: test@example.com"
// }
// ```

// ## If You Remove `ErrorOutput`
// ```rust
// Json(self.to_string())
// ```

// **Response:**
// ```json
// "email already exists: test@example.com"
// ```

// ## Key Differences

// | Aspect | With `ErrorOutput` | Without |
// |--------|-------------------|---------|
// | **Structure** | JSON object with `error` field | Plain JSON string |
// | **Content-Type** | `application/json` object | `application/json` string |
// | **Client Parsing** | `response.error` | `response` (raw string) |
// | **Consistency** | Structured API contract | Less predictable |
// | **Extensibility** | Easy to add `code`, `details`, etc. | Harder to extend |

// ## Example Client Code

// **With `ErrorOutput`:**
// ```javascript
// const res = await fetch('/api/signup', ...);
// const data = await res.json();
// console.log(data.error); // "email already exists: test@example.com"
// ```

// **Without `ErrorOutput`:**
// ```javascript
// const res = await fetch('/api/signup', ...);
// const data = await res.json();
// console.log(data); // "email already exists: test@example.com"
// ```

// ## My Recommendation

// **Keep `ErrorOutput`.** It's a best practice because:

// 1. **Consistency** — Success responses are objects (`{ token: "..." }`), errors should be too
// 2. **Extensibility** — Later you might want to add error codes, timestamps, or detailed info:
//    ```rust
//    #[derive(Debug, Serialize, Deserialize)]
//    pub struct ErrorOutput {
//        pub error: String,
//        pub code: String,
//        pub timestamp: DateTime<Utc>,
//    }
//    ```
// 3. **API Contract** — Clients know to always extract from `.error` field

// If you remove it, you sacrifice a clean API design for minimal savings (wrapping a string in an object is trivial).
