use thiserror::Error;
// thiserror crate, which simplifies creating custom error types by automatically implementing the standard library's std::error::Error and std::fmt::Display traits.

// Derives the necessary functionality. Debug allows the error to be formatted for debugging output, while Error triggers the thiserror macro.
// Defines an enumeration to hold different types of errors that can occur in the application. Each variant of the enum represents a specific error type, and the #[from] attribute allows for automatic conversion from the specified error type to our custom AppError.
#[derive(Error, Debug)]
pub enum AppError {
    #[error("sql error: {0}")]
    SqlxError(#[from] sqlx::Error),

    #[error("password hash error: {0}")]
    PasswordHashError(#[from] argon2::password_hash::Error),
}

// #[error("...")]: This attribute comes from thiserror and defines the display message for each specific error variant. The {0} interpolates the underlying error message.
// #[from]: This attribute (also from thiserror) automatically implements the From trait for the specified type. For example, #[from] sqlx::Error allows the code to easily convert a database error (sqlx::Error) into an AppError::SqlxError. This is especially useful when using the ? operator in Rust for error propagation.
// In summary, this code creates a unified AppError type that wraps both database (sqlx) and password hashing (argon2) errors, allowing them to be easily returned and handled throughout your application.

// question:
// #[error("sql error: {0}")]
// SqlxError(#[from] sqlx::Error),

// which means the error from sqlx::Error is converted into sql error: {sqlx::Error} by calling AppError::SqlxError, right?

// answer:
// Yes, that's correct! The #[from] attribute allows for automatic conversion from sqlx::Error to AppError::SqlxError. When you encounter an error of type sqlx::Error in your code, you can use the ? operator to automatically convert it into an AppError::SqlxError. The error message will then be formatted as "sql error: {0}", where {0} will be replaced with the actual error message from sqlx::Error.

// Yes, you have the right idea, but it does two distinct things:

// 1. **Type Conversion (`#[from]`)**: It automatically implements the `From` trait, so a `sqlx::Error` is converted into the enum variant `AppError::SqlxError(sqlx::Error)`. This allows you to use the `?` operator to automatically wrap database errors into your `AppError` type.

// 2. **String Formatting (`#[error(...)]`)**: It implements the `Display` trait. When you print or format an `AppError::SqlxError` as a string, it uses `"sql error: {0}"`, where `{0}` is replaced by the actual error message generated by the underlying `sqlx::Error`.

// sqlx::Error
// In Rust, external crates added to your Cargo.toml (like sqlx) are automatically available globally. You don't need a use statement just to access a crate, as long as you provide the path.
// You are using the fully qualified path inline: sqlx::Error. Because you explicitly mention the crate name sqlx right where you use it, no use statement is needed.

// SqlxError(#[from] sqlx::Error)
// thiserror does not generate a bunch of From implementations for each variant of sqlx::Error. Instead, it generates exactly one From trait implementation for the entire sqlx::Error type:
// impl From<sqlx::Error> for AppError {
//     fn from(err: sqlx::Error) -> Self {
//         AppError::SqlxError(err)
//     }
// }
// Since sqlx::Error itself is an enum, any of its internal variants (like RowNotFound or Database) are already contained within the sqlx::Error type. The From trait simply takes that whole sqlx::Error enum instance and wraps it inside your AppError::SqlxError variant.

// question:
// #[error("sql error: {0}")]
// SqlxError(#[from] sqlx::Error),

// so, AppError::SqlxError acts like a wrapper or a pointer which points to the sqlx::Error, and #[error("sql error: {0}")] calls the display implementations of each variants of sqlx::Error correspondantly, right?

// answer:
// Yes, you are exactly right!

// To be precise:

// 1. **It's a Wrapper**: `AppError::SqlxError` acts as a direct wrapper (an enum variant containing the value) rather than a pointer. It actually owns and stores the underlying `sqlx::Error` instance inside it: `AppError::SqlxError(sqlx::Error)`.
// 2. **Delegating `Display`**: The `#[error("sql error: {0}")]` attribute tells `thiserror` how to format this specific variant. The `{0}` references the first (and only) field inside the tuple struct variant. When you print the `AppError`, it delegates the `{0}` part directly to the underlying `sqlx::Error`'s own `Display` implementation.

// So if `sqlx::Error` was a `RowNotFound` variant, printing your `AppError` would output: `"sql error: no rows returned by a query that expected to return at least one row"`.
