mod user;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

pub use user::{CreateUser, SigninUser};

#[derive(Debug, Clone, FromRow, Serialize, Deserialize, PartialEq)]
pub struct User {
    pub id: i64,          // 1, 2, 3, ... (auto-generated by database)
    pub fullname: String, //  "Hui Lin".to_string(), // User must have a name
    pub email: String,    // "hl@email.com".to_string(), // User must have email (identification)
    // #[sqlx(default), serde(skip)] // combine multiple attributes on the same line using a comma separator.
    #[sqlx(default)]
    // This instructs the sqlx::FromRow macro to fall back to the type's default value if the query does not return a password_hash column. Since the type is Option<String>, the default is None. This is useful because it allows you to query the database for a User without being forced to always select the password_hash column (e.g., when you just need the user's public profile data).
    #[serde(skip)]
    // This instructs the serde crate's Serialize and Deserialize macros to completely ignore this field. When you convert the User struct into JSON (or another format) to send to a client, the password_hash will not be included. This is a crucial security practice to ensure password hashes are never accidentally exposed via an API.
    pub password_hash: Option<String>, // Some("hashed_value".to_string()), // User might use OAuth or SSO or simply hasn't set a password yet, so this field can be None.
    pub created_at: DateTime<Utc>, // Utc::now()
}
// question:
// is it necessary for the mod.rs separates the User definition from it's methods defined in the user.rs? what is design pattern of that?

// answer:
// it is not strictly necessary. In Rust, you can define a struct and its impl block in the exact same file. Doing so is actually the most common approach for smaller types.
// Separating the data definition (mod.rs) from its behavior/methods (user.rs) is an organizational choice rather than a formal gang-of-four design pattern. It aligns with a few software design principles:
// Separation of Concerns: mod.rs defines the raw data structure (an Entity or Data Transfer Object), while user.rs contains the business logic and database operations (acting like a Data Access Object or Repository pattern).
// Module Facade: By defining or re-exporting the models in the mod.rs file, you create a clean public API for the models module. Other parts of the app can simply use crate::models::User; instead of knowing the internal file structure.
// File Size Management: As an application grows, database queries, password hashing, and unit tests can make a file quite large. Moving the implementation to a separate file keeps the module index (mod.rs) easy to read at a glance.
// In summary, while it's not a strict requirement, this organizational pattern can help maintain clarity and manageability as your codebase grows.

// pub email: String,
// If you wanted to enforce email formatting via macro attributes, developers typically use a crate like validator. You would add the crate and then apply an attribute like this:
// Requires the `validator` crate
// #[derive(Validate)]
// pub struct User {
// ...
// #[validate(email)]
//     pub email: String,
// ...
// }

// The best solution is a multi-layered approach, often referred to as **Defense in Depth**, which utilizes both application-level and database-level validation.

// 1. **Application Level (Rust Structs/Methods):**
//    Validating early in the application—either by using the `validator` crate or the "Newtype" pattern (e.g., creating a custom `struct Email(String)` that validates upon instantiation)—is recommended. This provides fast feedback, produces user-friendly error messages, and avoids unnecessary database calls with invalid data.

// 2. **Database Level (SQL Constraints):**
//    Applying a `CHECK` constraint (such as a regex pattern for emails) in the database acts as the final line of defense. This guarantees data integrity, ensuring that invalid emails cannot be inserted even if a bug bypasses application logic or if data is inserted manually via other tools.

// Using both ensures early error detection in the backend while maintaining absolute data integrity in the storage layer.

// # Why `password_hash` is `Option<String>` While Others Are `String`

// ## The Reason

// **`password_hash` is optional because users can exist in your system without having set a password yet.**

// ### Use Cases for `None` Password Hash

// ```rust
// pub password_hash: Option<String>,
// ```

// **Scenario 1: Social Login / OAuth**
// ```
// User signs up via Google OAuth
//     ↓
// User created in database
//     ↓
// No password_hash needed (password-less authentication)
//     ↓
// password_hash = None
// ```

// **Scenario 2: Account Creation Flow**
// ```
// User registers email address
//     ↓
// Verification email sent
//     ↓
// User not yet verified → temporarily no password
//     ↓
// password_hash = None
//     ↓
// User clicks verification link and sets password
//     ↓
// password_hash = Some("hashed_value")
// ```

// **Scenario 3: Admin-Created Accounts**
// ```
// Admin creates user account for new employee
//     ↓
// Temporary credentials sent to user
//     ↓
// User hasn't set personal password yet
//     ↓
// password_hash = None initially
// ```

// ## Why `fullname` and `email` Are NOT Optional

// ```rust
// pub fullname: String,  // Always required
// pub email: String,     // Always required
// ```

// These are **core identifying information** - every user must have:
// - **Email** - Primary way to identify/contact the user
// - **Fullname** - Basic profile information

// Without email, you can't even identify who the user is. Without fullname, the user profile is incomplete.

// ## The Pattern

// ```rust
// #[derive(Debug, Clone, FromRow, Serialize, Deserialize, PartialEq)]
// pub struct User {
//     pub id: i64,                              // ← Database generated, never None
//     pub fullname: String,                     // ← User profile, always required
//     pub email: String,                        // ← Identification, always required

//     #[sqlx(default)]
//     #[serde(skip)]
//     pub password_hash: Option<String>,        // ← Auth credential, can be None

//     pub created_at: DateTime<Utc>,            // ← System field, always present
// }
// ```

// ## Database Schema Reflection

// ```sql
// CREATE TABLE users (
//     id BIGINT PRIMARY KEY,
//     fullname VARCHAR NOT NULL,        -- Required column
//     email VARCHAR NOT NULL,           -- Required column
//     password_hash VARCHAR,            -- Optional column (NULL allowed)
//     created_at TIMESTAMP NOT NULL
// );
// ```

// The `#[sqlx(default)]` attribute handles this:

// ```rust
// #[sqlx(default)]
// pub password_hash: Option<String>,
// ```

// When querying without selecting `password_hash`, `sqlx` automatically sets it to `None` rather than failing.

// ## Summary Table

// | Field | Type | Required? | Why |
// |-------|------|-----------|-----|
// | `id` | `i64` | Yes | Auto-generated by database |
// | `fullname` | `String` | Yes | Core profile data |
// | `email` | `String` | Yes | User identification |
// | `password_hash` | `Option<String>` | No | Users may use OAuth, SSO, or not set password yet |
// | `created_at` | `DateTime<Utc>` | Yes | System metadata |

// **The `Option<T>` pattern in Rust is the idiomatic way to represent "this field might not have a value."**

// Why created_at: DateTime<Utc> Is Always NOT NULL
// The Reason
// created_at is a system-generated timestamp that is automatically set when a user is created.

// Unlike password_hash (which may be intentionally absent), created_at is always populated because:

// Automatic timestamp - Set by the application or database
// Record metadata - Tracks when the user account was created
// Audit trail - Essential for compliance, debugging, and analytics

// CREATE TABLE users (
//     id BIGINT PRIMARY KEY,
//     fullname VARCHAR NOT NULL,
//     email VARCHAR NOT NULL,
//     password_hash VARCHAR,              -- Optional
//     created_at TIMESTAMP NOT NULL
//                DEFAULT CURRENT_TIMESTAMP  -- ← Auto-set by DB
// );

// Pattern: System-managed metadata fields (timestamps) are required. User-controlled optional data fields use Option<T>.
